Enhance the Frontend & Make it more Attractive
SanjayMarreddi/ML_Internship_Technocolabs pull request #40
Opened 2021-01-30 20:00 UTC by anushavc

#### Issue Number
ISSUE #4 

#### Describe the changes you've made

I have made changes to all the HTML files and the style.css file to enhance the frontend of the project.  I have added a new svg file which I have used in the start.html.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Additional context (OPTIONAL)

#### Test plan (OPTIONAL)

#### Checklist

- [x] My code follows the code style of this project.
- [x] I have performed a self-review of my own code.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] The title of my pull request is a short description of the requested changes.

2021-01-31 14:24 UTC, SanjayMarreddi requested changes
@anushavc Overall It looks good. Here are few suggestions for the Home Page (`Start.html`) :-
 - There are 3 boxes right, Reduce the dimensions of the last 2 boxes & their content accordingly.
 - Also, keep all the 3 boxes align in center position of the web page. (Currently, They look aligned towards right side.)
 - It would be better if you could even add some related Images to impose interest to user's to use our project.
 
 Good Luck !!

2021-02-09 13:57 UTC, anushavc commented
I have made the suggested changes. Do let me know if I need to make any more

2021-02-09 15:31 UTC, SanjayMarreddi requested changes
@anushavc Everything is alright. Just look at the below 2 slight Modifications

2021-02-09 15:31 UTC, SanjayMarreddi commented on templates/Start.html
> +    <p style="font-size:xx-large;" >About the project</p>
Change the line as follows 
`<p style="font-size:xx-large;" >Glimpse of the project !</p>`

2021-02-09 15:31 UTC, SanjayMarreddi commented on templates/Start.html
> +    <p style="font-size:x-large;" >To detect your emotion using the webcam feed</p>
Remove the line number `111`

2021-02-09 16:07 UTC, SanjayMarreddi approved these changes

2021-02-09 16:07 UTC, merged