Trained the model for avengers
SanjayMarreddi/ML_Internship_Technocolabs pull request #41
Opened 2021-02-03 11:27 UTC by Amit366

#### Issue Number
ISSUE #9 

#### Describe the changes you've made
The model is trained to identify some of the avengers.

2021-02-04 10:26 UTC, Amit366 commented
@SanjayMarreddi sir please review it fast as only few days are left for the competition

2021-02-04 10:43 UTC, SanjayMarreddi requested changes
@Amit366 It looks fine. Please make the slight modifications as suggested below :

- Make a Folder named `Basic_Avengers_Recognition`  under the `Facial_Recognition_Models/Using_Standard_Libraries` and then upload all your files there.
- Explain the difficult steps in the `script.py` file with inline Comments for better understanding.
-  Also briefly explain the Working of the Model & Classifications it can make in the README of newly created folder as said above.
- Make a Screen Recording while running the Model on your system & do keep a link of Video Demo in your README.
- You can refer to the README [here](https://github.com/SanjayMarreddi/Facial-Expression-Recognition-Classifier-Model/blob/master/Facial_Recognition_Models/Using_Standard_Libraries/Bharath_C_S/README.md) for an idea.

Good Luck !!

2021-02-04 10:43 UTC, SanjayMarreddi commented on Face_Recognition/Readme.md
> +The project asks the user for input and in the given photo if the above mentioned images are present then it represents the face with a rectangule with the name on it.
Do correct the `rectangle` typo.
Also You can briefly describe a bit about the Model here.

2021-02-04 10:50 UTC, Amit366 commented
@SanjayMarreddi sir video recording isn't possible as on the running the script it asks the user to provide the image and from that image it shows whether the trained image is present or not.

2021-02-04 10:51 UTC, Amit366 commented
@SanjayMarreddi I will update the remaining changes

2021-02-04 11:31 UTC, Amit366 commented
@SanjayMarreddi I have updated it. Please review it.

2021-02-04 13:49 UTC, SanjayMarreddi requested changes
@Amit366 Now everything looks fine. But I asked you to put the `Basic_Avengers_Recognition` folder inside this `Facial-Expression-Recognition-Classifier-Model/Facial_Recognition_Models/Using_Standard_Libraries`.

Not under `Bharath_C_S`. Keep it as parallel to this.

Just make that modification.

2021-02-04 17:22 UTC, Amit366 commented
@SanjayMarreddi done sir. Please review it.

2021-02-05 07:08 UTC, SanjayMarreddi approved these changes

2021-02-05 07:08 UTC, merged